version: '3.7'
services:
  mysql_con:
    container_name: mysql_cont
    build:
     context: .
     dockerfile: build/mysql_con/Dockerfile
     args:
      - mysql_user
      - mysql_pass
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_pass}
      - MYSQL_ROOT_PASSWORD=${mysql_pass}
      - MYSQL_DATABASE=image_blog
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  image_blog:
    container_name: image_blog_con
    build:
     context: .
     dockerfile: build/image_blog/Dockerfile
     args:
      - mysql_user
      - mysql_pass
    ports:
     - "8000:8000"
    depends_on:
     - mysql_con
    command: ["/go/Image_blog_go/wait-for-it.sh", "mysql_con:3306", "-t", "60", "--", "/go/Image_blog_go/Image_blog_go"]
    links:
     - mysql_con
    volumes:
      - image_blog_data:/go/Image_blog_go/data
volumes:
  image_blog_data:
